server:
  port: 8092
  servlet:
    context-path: /patient

swagger:
  url: https://localhost:8092/patient
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
logging:
  file:
    name: inventory.log
  pattern:
    console: '%d %-5level %logger : %msg%n'
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    '[org.springframework.web]': INFO
    '[com.ros.inventory]': DEBUG
    '[org.hibernate]': INFO
